#!/bin/sh

set -e

if [ $# -ne 1 ] ; then
	echo "Incorrect number of parameters.\nUsage:\n\tod-update <data_dir>"
	exit 1
fi

BOOTLD=$1/ubiboot.bin
KERNEL=$1/uzImage.bin
ROOTFS=$1/rootfs.squashfs

if [ -r $ROOTFS ] ; then
	echo "Updating rootfs..."
	cp $ROOTFS /boot/update_r.bin
fi

if [ -r $BOOTLD ] ; then
	echo "Updating bootloader..."
	flash_erase /dev/mtd0 0 1
	nandwrite -p /dev/mtd0 $BOOTLD
fi

if [ -r $KERNEL ] ; then
	KERNEL_BAK_ID=`ubinfo -d 0 -N kernel_bak |head -n1 |sed "s/.*\(\d\+\) .*/\1/"`
	echo "Updating kernel..."
	ubiupdatevol /dev/ubi0_$KERNEL_BAK_ID $KERNEL
	ubirename /dev/ubi0 kernel kernel_bak kernel_bak kernel
fi

exit 0
