#!/bin/sh

if [ "$1" != "start" ] ; then exit 0; fi

export DIALOGOPTS="--colors --backtitle \"\Zb\Z3OpenDingux Flasher\Zn\""
echo "screen_color = (RED,RED,ON)" > /tmp/dialog_err.rc

DISCLAIMER="\Zb\Z3IMPORTANT NOTICE\Zn

By using this software, you agree
that its authors are not liable in
any way in case of damage to your
device, your data, or yourself.
Use it at your own risk.

Do you agree with these terms?"

dialog --defaultno --yesno "$DISCLAIMER" 13 38
if [ $? -eq 1 ] ; then
	reboot
	exit 1
fi

MODEL=`sed 's/^.*--.*model=\([[:alnum:]]\+\).*$/\1/' /proc/cmdline`
VARIANT=`sed 's/^.*--.*hwvariant=\([[:alnum:]]\+\).*$/\1/' /proc/cmdline`

MODELMSG="Found the following device:

Model:   ${MODEL}
Variant: ${VARIANT}

Is this correct?"

dialog --defaultno --yesno "$MODELMSG" 10 42
if [ $? -eq 1 ] ; then
	reboot
	exit 1
fi

UBIBOOT=/usr/share/opendingux/ubiboot-${MODEL}_${VARIANT}.bin

if [ ! -f "${UBIBOOT}" ] ; then
	DIALOGRC="/tmp/dialog_err.rc" \
		dialog --msgbox 'ERROR!\n\nUnable to find bootloader.' 7 30
	exit 1
fi

echo "Installing bootloader..."
flash_erase /dev/mtd0 0 1
nandwrite -p /dev/mtd0 ${UBIBOOT}

echo "Formatting NAND..."
ubiformat /dev/mtd1 -y
ubiattach -m1
ubimkvol /dev/ubi0 -s 16MiB -N kernel
ubimkvol /dev/ubi0 -s 16MiB -N kernel_bak
ubimkvol /dev/ubi0 -m -N rootfs
ubiupdatevol /dev/ubi0_2 -t

echo "Installing mininit..."
mount -t ubifs ubi0:rootfs /boot
mkdir -p /boot/root /boot/dev
cp /usr/share/opendingux/mininit-syspart /boot

echo "Configuring USB..."
mkdir /sys/kernel/config/usb_gadget/c1
mkdir /sys/kernel/config/usb_gadget/c1/strings/0x409
mkdir /sys/kernel/config/usb_gadget/c1/configs/c.1
mkdir /sys/kernel/config/usb_gadget/c1/functions/ffs.ffs

echo 0x601a > /sys/kernel/config/usb_gadget/c1/idVendor
echo 0x4750 > /sys/kernel/config/usb_gadget/c1/idProduct
echo "Ingenic" > /sys/kernel/config/usb_gadget/c1/strings/0x409/manufacturer
echo "odbootd" > /sys/kernel/config/usb_gadget/c1/strings/0x409/product
ln -s /sys/kernel/config/usb_gadget/c1/functions/ffs.ffs /sys/kernel/config/usb_gadget/c1/configs/c.1/ffs.ffs

mkdir /dev/ffs
mount ffs -t functionfs /dev/ffs

echo "Obtain rootfs and kernel from USB..."
/usr/sbin/odbootd /dev/ffs /sys/kernel/config/usb_gadget/c1/UDC musb-hdrc.0.auto

echo "Flashing kernel..."
ubiupdatevol /dev/ubi0_0 /boot/uzImage.bin
ubiupdatevol /dev/ubi0_1 /boot/uzImage.bin

dialog --msgbox 'Installation succeded!\nThe device will reboot now.' 7 28
reboot
exit 0
